[package]
name = "icedit"
version = "0.1.0"
edition = "2021"

[dependencies]
ropey = "1.6"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
crossterm = "0.27"
unicode-width = "0.1"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
