[package]
name = "icedit-core"
version = "0.1.0"
edition = "2021"
description = "Core functionality for the IcEdit text editor"

[dependencies]
ropey = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
